### ISSUE TITLE
Setup testing with jmeter

### ISSUE THREAD

**Issue by admiralAwkbar** [LukasPersonal/actions-demo#20]
```yml
on:
  push:

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Jmeter
    # Set the agent to run on
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
- name: Run JMeter Tests
  uses: rbhadti94/apache-jmeter-action@v0.3.1
  with:
    testFilePath: tests/sample_test.jmx
    outputReportsFolder: reports/
```
